### ISSUE TITLE
Java de/serialization of stream of objects

### ISSUE THREAD

**Issue by DatPhanTien** [kiat/serialization#1]
Dear,

Thanks for your exciting project.
While reading through your tested methods, one question come to our mind.
That is what would be the best JAVA serialization/deserialization method when it comes to stream?

Assuming that we have API that returns a stream of objects (and the reason for returning a stream is mostly because that it would not fit within the JAVA heap).
When consuming this API, if the serialization/deserialization is needed, what would be the best approach? Given that using one ByteArrayOutputStream is not suitable since the memory size is not enough (ByteArrayOutputStream stores serialized objects in-memory).

Would you make a stream of ByteArrayOutputStream or would you have a better solution for this case?

**Comment by kiat** [comment]
Hi, 

This project is described in details in our paper about it here 
https://dl.acm.org/citation.cfm?doid=3127479.3129248 

You ask a very important question. 
The first thing that you should consider in stream processing is to not redo things each time, like not re-serialize the data again. This is important when you work with data windows (like a sliding window).

Another question is how large is your object that you want to serialize and write into stream. If the object is very large that is not fitting into heap then this approach will not work and you need to chunk the object and work with disk. 

Assuming that the objects can fit into heap, and you work with a sliding window, then you can generate byte array  like  byte[] and write it each time to outputstream like you would write into disk. 
In our project this is implemented, when we send objects from 10 clients to a server and calculate the time for it. 

If I remember correctly, you can see here 
https://github.com/kiat/serialization/blob/de51a9195f5d77a589c239594b218205d5ff9a2f/Java/src/main/java/edu/rice/pdb/serial/networking/SocketClient.java#L419
We allocate a large page, serialize objects into it and then send the page over to the server. 
Sending pages is more efficient than sending over single objects. But this depends on your application. 

Let me know if it is clear or you have any further questions. 

Thanks,
Kia
